"""create initial tables

Revision ID: f2a560c8fba2
Revises: 
Create Date: 2026-06-14 14:11:51.707725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a560c8fba2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_username', sa.String(length=39), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('profile_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    op.create_index(op.f('ix_developers_github_username'), 'developers', ['github_username'], unique=True)
    op.create_table('skill_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('skill_key', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trajectory', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_nodes_developer_id'), 'skill_nodes', ['developer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_nodes_developer_id'), table_name='skill_nodes')
    op.drop_table('skill_nodes')
    op.drop_index(op.f('ix_developers_github_username'), table_name='developers')
    op.drop_table('developers')
    # ### end Alembic commands ###
